<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_ALIAS' => 'Алиас',
    'ATTR_CONTENT' => 'Контент',
    'ATTR_CREATED' => 'Создан',
    'ATTR_ID' => 'ID',
    'ATTR_IMAGE_URL' => 'Изображение',
    'ATTR_PREVIEW_URL' => 'Мини-изображение',
    'ATTR_SNIPPET' => 'Введение',
    'ATTR_STATUS' => 'Статус',
    'ATTR_TITLE' => 'Заголовок',
    'ATTR_UPDATED' => 'Обновлён',
    'ATTR_VIEWS' => 'Просмотры',
    'BACKEND_CANCEL_BTN_TITLE' => 'Отмена',
    'BACKEND_CREATE_SUBMIT' => 'Сохранить',
    'BACKEND_CREATE_SUBTITLE' => 'Создание поста',
    'BACKEND_CREATE_TITLE' => 'Блоги',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Не удалось сохранить пост. Попробуйте пожалуйста еще раз!',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Не удалось обновить пост. Попробуйте пожалуйста еще раз!',
    'BACKEND_INDEX_SUBTITLE' => 'Список постов',
    'BACKEND_INDEX_TITLE' => 'Блоги',
    'BACKEND_PROMPT_STATUS' => 'Выберите статус',
    'BACKEND_UPDATE_SUBMIT' => 'Обновить',
    'BACKEND_UPDATE_SUBTITLE' => 'Обновление поста',
    'BACKEND_UPDATE_TITLE' => 'Блоги',
    'FRONTEND_INDEX_READ_MORE_BTN' => 'Читать далее',
    'FRONTEND_INDEX_TITLE' => 'Блоги',
    'STATUS_PUBLISHED' => 'Опубликован',
    'STATUS_UNPUBLISHED' => 'Не опубликован',
];
