<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_ALIAS' => 'Alias',
    'ATTR_CONTENT' => 'Text',
    'ATTR_CREATED' => 'Angelegt am',
    'ATTR_ID' => 'ID',
    'ATTR_IMAGE_URL' => 'Image',
    'ATTR_PREVIEW_URL' => 'Vorschau',
    'ATTR_SNIPPET' => 'Einführung',
    'ATTR_STATUS' => 'Status',
    'ATTR_TITLE' => 'Titel',
    'ATTR_UPDATED' => 'Geändert am',
    'ATTR_VIEWS' => 'Ansichten',
    'BACKEND_CANCEL_BTN_TITLE' => 'Abbrechen',
    'BACKEND_CREATE_SUBMIT' => 'Speichern',
    'BACKEND_CREATE_SUBTITLE' => 'Post anlegen',
    'BACKEND_CREATE_TITLE' => 'Blogs',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Post wurde nicht gespeichert. Bitte nochmals versuchen!',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Post wurde nicht geändert. Bitte nochmals versuchen!',
    'BACKEND_INDEX_SUBTITLE' => 'Post-Liste',
    'BACKEND_INDEX_TITLE' => 'Blogs',
    'BACKEND_PROMPT_STATUS' => 'Wähle einen Status',
    'BACKEND_UPDATE_SUBMIT' => 'Ändern',
    'BACKEND_UPDATE_SUBTITLE' => 'Post ändern',
    'BACKEND_UPDATE_TITLE' => 'Blogs',
    'FRONTEND_INDEX_READ_MORE_BTN' => 'Lies mehr',
    'FRONTEND_INDEX_TITLE' => 'Blogs',
    'STATUS_PUBLISHED' => 'Veröffentlicht',
    'STATUS_UNPUBLISHED' => 'Nicht veröffentlicht',
];
