<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_ALIAS' => 'Alias',
    'ATTR_CONTENT' => 'Text',
    'ATTR_CREATED' => 'Created at',
    'ATTR_ID' => 'ID',
    'ATTR_IMAGE_URL' => 'Image',
    'ATTR_PREVIEW_URL' => 'Preview',
    'ATTR_SNIPPET' => 'Intro',
    'ATTR_STATUS' => 'Status',
    'ATTR_TITLE' => 'Title',
    'ATTR_UPDATED' => 'Updated at',
    'ATTR_VIEWS' => 'Views',
    'BACKEND_CANCEL_BTN_TITLE' => 'Cancel',
    'BACKEND_CREATE_SUBMIT' => 'Save',
    'BACKEND_CREATE_SUBTITLE' => 'Post creating',
    'BACKEND_CREATE_TITLE' => 'Blogs',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Post has not been saved. Please try again!',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Post has not been updated. Please try again!',
    'BACKEND_INDEX_SUBTITLE' => 'Posts list',
    'BACKEND_INDEX_TITLE' => 'Blogs',
    'BACKEND_PROMPT_STATUS' => 'Choose a status',
    'BACKEND_UPDATE_SUBMIT' => 'Update',
    'BACKEND_UPDATE_SUBTITLE' => 'Post updating',
    'BACKEND_UPDATE_TITLE' => 'Blogs',
    'FRONTEND_INDEX_READ_MORE_BTN' => 'Read More',
    'FRONTEND_INDEX_TITLE' => 'Blogs',
    'STATUS_PUBLISHED' => 'Published',
    'STATUS_UNPUBLISHED' => 'Unpublished',
];
