<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_ALIAS' => 'Subtitulo',
    'ATTR_CONTENT' => 'Texto',
    'ATTR_CREATED' => 'Criado em',
    'ATTR_ID' => 'ID',
    'ATTR_IMAGE_URL' => 'Imagem',
    'ATTR_PREVIEW_URL' => 'Visualizar',
    'ATTR_SNIPPET' => 'Introdução',
    'ATTR_STATUS' => 'Status',
    'ATTR_TITLE' => 'Título',
    'ATTR_UPDATED' => 'Atualizado em',
    'ATTR_VIEWS' => 'Visualizações',
    'BACKEND_CANCEL_BTN_TITLE' => 'Cancelar',
    'BACKEND_CREATE_SUBMIT' => 'Salvar',
    'BACKEND_CREATE_SUBTITLE' => 'Criando postagem',
    'BACKEND_CREATE_TITLE' => 'Blogs',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Post não foi salvo. Por favor tente novamente!',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Post não foi atualizado. Por favor tente novamente!',
    'BACKEND_INDEX_SUBTITLE' => 'Lista de postagens',
    'BACKEND_INDEX_TITLE' => 'Blogs',
    'BACKEND_PROMPT_STATUS' => 'Escolha um status',
    'BACKEND_UPDATE_SUBMIT' => 'Atualizar',
    'BACKEND_UPDATE_SUBTITLE' => 'Atualizando postagem',
    'BACKEND_UPDATE_TITLE' => 'Blogs',
    'FRONTEND_INDEX_READ_MORE_BTN' => 'Leia mais',
    'FRONTEND_INDEX_TITLE' => 'Blogs',
    'STATUS_PUBLISHED' => 'Publicado',
    'STATUS_UNPUBLISHED' => 'Não publicado',
];
